name: Build & Upload Debug APK to Google Drive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Install gdrive CLI
        run: |
          sudo apt-get update
          wget -O gdrive \
            https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/gdrive

      - name: Upload APK to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          echo "$GDRIVE_CREDENTIALS" > service-account.json
          gdrive upload \
            --service-account service-account.json \
            --parent 1gHXMfzb-WD78udXwporCmaa_9yd6sklJ \
            build/app/outputs/flutter-apk/app-debug.apk
