name: Build & Upload Debug APK to Google Drive

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Flutter (latest stable that meets SDK requirements)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Accept Android licenses
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      # 5. Build debug APK
      - name: Build debug APK
        run: flutter build apk --debug

      # 6. Install rclone (Google Drive supported)
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 7. Configure rclone from secret
      - name: Configure rclone
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      # 8. Upload APK to Google Drive folder
      - name: Upload APK to Google Drive
        run: |
          rclone copy build/app/outputs/flutter-apk/app-debug.apk gdrive:FlutterAPKFolder
